### ISSUE TITLE
SVG output?

### ISSUE THREAD

**Issue by fjansson** [ldo/qahirah#7]
Is it possible to draw to an SVGSurface with qahirah and save as the result an svg file?
I found that I can create a surface with 
```
pix = qah.SVGSurface.create(filename = "test.svg", dimensions_in_points = (600, 600)) 
```
and draw to it - I tried this in the paths example. The output file is created but remains empty.
So, is SVG output supported, and is there a function that should be called at the end to actually write the file?

**Comment by ldo** [comment]
Yes, SVG does work, but there is a trickiness with these non-bitmap surfaces: Cairo doesn’t flush the output until the objects are deleted. Since the Context retains a reference to the Surface, you need to make sure **both** objects are disposed. There is no explicit `flush` call I have found that works.

Enclosed is an example that demonstrates this. The last line is crucial.

[qahirah_svg_example.zip](https://github.com/ldo/qahirah/files/1592211/qahirah_svg_example.zip)

**Comment by fjansson** [comment]
Thank you! This worked for me, I got an svg. Your example generates a nice svg with a path object. 
However, my own code resulted in an svg containing an embedded raster image, which is not what I want. I post this in case someone else is confused over this. It seems this command, which I had in my own test code and which is present in the `paths` example, forces cairo to generate a raster image:
```
ctx.set_operator(CAIRO.OPERATOR_SOURCE)
```
Without it, the svg is generated with vector objects instead. I guess some composing operations are not implemented or not possible to export as vector svg - I don't need them for anything, it was just in the script to initially clear the image.
